GET http://localhost:5247/todos/
Content-Type: application/json
Authorization: Bearer <your_token_here>

###

POST http://localhost:5247/todos/
Content-Type: application/json

{
    "title": "Prepare presentations for ConFoo",
    "dueDate": "2025-02-22T23:59:59",
    "isCompleted": false
}

###

DELETE http://localhost:5247/todos/3

###
GET http://localhost:5247/todos/2

###
POST http://localhost:5247/login/
Content-Type: application/json

{
    "Username": "admin",
    "Password": "admin",
    "Email": "admin@admin.com",
    "GivenName": "Admin",
    "FamilyName": "Admin"
}